### ISSUE TITLE
Error at fetch testcase from atcoder (old contest)

### ISSUE THREAD

**Issue by fumiphys** [fumiphys/programming_contest#1]
error message: 
```
Traceback (most recent call last):
  File "/Users/fkiyozawa/github/programming_contest/utils/atcoder/fetch_testcase.py", line 35, in <module>
    writer.write(inp.nextSibling.text)
  File "/usr/local/lib/python3.7/site-packages/bs4/element.py", line 797, in __getattr__
    self.__class__.__name__, attr))
AttributeError: 'NavigableString' object has no attribute 'text'
```

**Comment by fumiphys** [comment]
fixed at 7dc5af65a129637c80915ed0c7b2e55b9c7bd56e .
